import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import styles from './layout.module.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <header className={styles.header}>
        <h1>header title</h1>
        <nav className={styles.nav}>
          <a href="/">home</a>
          <a href="/about">about</a>
          <a href="/posts">posts</a>
          <a href="/contact">contact</a>
        </nav>
      </header>
      {children}
      <footer>
        footer section
      </footer>
      </body>
    </html>
  )
}
